[package]
name = "rmote"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.42", features = ["derive", "env"] }
librsync = "0.2.3"
notify = { version = "8.1.0", features = ["serde"] }
ssh2 = { version = "0.9.5", features = ["vendored-openssl"] }
